In [1]:
import pandas as pd
import numpy as np

## EDA of user data

In [3]:
df_user0= pd.read_csv(r"C:\Users\gudql\Desktop\B4AFTER\B4AFTER-Back-\books\csv\Newbooks.csv")

In [4]:
df_user0.shape

(1031131, 11)

In [5]:
df_user0.head()

,user_id,isbn,rating,book_title,book_author,year_of_publication,book_publisher,img_l,Summary,Language,Category
0,2,195153448,0,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,Provides an introduction to classical myths pl...,en,['Social Science']
1,8,2005018,5,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses']
2,11400,2005018,0,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses']
3,11676,2005018,8,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses']
4,41385,2005018,0,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses']

## data Null check

In [6]:
df_user0.drop(index=df_user0[df_user0['Category'] == '9'].index, inplace=True) #remove 9 in category

df_user0.drop(index=df_user0[df_user0['rating'] == 0].index, inplace=True) #remove 0 in rating

In [7]:
print("Null check")
print("============================")
print("user_id: ", df_user0.user_id.isnull().sum())
print("isbn: ", df_user0.isbn.isnull().sum())
print("book_title: ", df_user0.book_title.isnull().sum())
print("book_author: ", df_user0.book_author.isnull().sum())
print("year_of_publication: ", df_user0.year_of_publication.isnull().sum())
print("book_publisher: ", df_user0.book_publisher.isnull().sum())
print("Summary: ", df_user0.Summary.isnull().sum())
print("Category: ", df_user0.Category.isnull().sum())

Null check
============================
user_id:  0
isbn:  0
book_title:  0
book_author:  0
year_of_publication:  0
book_publisher:  0
Summary:  0
Category:  0

In [8]:
df_user0

,user_id,isbn,rating,book_title,book_author,year_of_publication,book_publisher,img_l,Summary,Language,Category
1,8,2005018,5,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses']
3,11676,2005018,8,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses']
5,67544,2005018,8,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses']
8,116866,2005018,9,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses']
9,123629,2005018,9,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct...",en,['Actresses']
...,...,...,...,...,...,...,...,...,...,...,...
1031107,278713,670528951,8,Orson Welles,Barbara Leaming,1985,Penguin USA,http://images.amazon.com/images/P/0670528951.0...,"Based on two years of interviews and research,...",en,['Biography & Autobiography']
1031118,278843,689818904,7,My Grandmother's Journey,John Cech,1998,Aladdin,http://images.amazon.com/images/P/0689818904.0...,A grandmother tells the story of her eventful ...,en,['Juvenile Fiction']
1031125,278851,067161746X,7,The Bachelor Home Companion: A Practical Guide...,P.J. O'Rourke,1987,Pocket Books,http://images.amazon.com/images/P/067161746X.0...,A tongue-in-cheek survival guide for single pe...,en,['Humor']
1031127,278851,767907566,5,All Elevations Unknown: An Adventure in the He...,Sam Lightner,2001,Broadway Books,http://images.amazon.com/images/P/0767907566.0...,A daring twist on the travel-adventure genre t...,en,['Nature']
1031129,278851,912333022,7,The Are You Being Served? Stories: 'Camping In...,Jeremy Lloyd,1997,Kqed Books,http://images.amazon.com/images/P/0912333022.0...,These hilarious stories by the creator of publ...,en,['Fiction']

In [9]:
df_user0.to_csv(r"C:\Users\gudql\Desktop\B4AFTER\B4AFTER-Back-\books\csv\proc_books.csv")